# CMake generated Testfile for 
# Source directory: C:/src/content-assimilation-engine/omni
# Build directory: C:/src/content-assimilation-engine/omni/aws
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[put]=] "C:/src/content-assimilation-engine/omni/aws/Debug/wrp.exe" "put" "../test/posix.yml")
  set_tests_properties([=[put]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/src/content-assimilation-engine/omni/CMakeLists.txt;97;add_test;C:/src/content-assimilation-engine/omni/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[put]=] "C:/src/content-assimilation-engine/omni/aws/Release/wrp.exe" "put" "../test/posix.yml")
  set_tests_properties([=[put]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/src/content-assimilation-engine/omni/CMakeLists.txt;97;add_test;C:/src/content-assimilation-engine/omni/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[put]=] "C:/src/content-assimilation-engine/omni/aws/MinSizeRel/wrp.exe" "put" "../test/posix.yml")
  set_tests_properties([=[put]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/src/content-assimilation-engine/omni/CMakeLists.txt;97;add_test;C:/src/content-assimilation-engine/omni/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[put]=] "C:/src/content-assimilation-engine/omni/aws/RelWithDebInfo/wrp.exe" "put" "../test/posix.yml")
  set_tests_properties([=[put]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/src/content-assimilation-engine/omni/CMakeLists.txt;97;add_test;C:/src/content-assimilation-engine/omni/CMakeLists.txt;0;")
else()
  add_test([=[put]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[get]=] "C:/src/content-assimilation-engine/omni/aws/Debug/wrp.exe" "get" "cae")
  set_tests_properties([=[get]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/src/content-assimilation-engine/omni/CMakeLists.txt;99;add_test;C:/src/content-assimilation-engine/omni/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[get]=] "C:/src/content-assimilation-engine/omni/aws/Release/wrp.exe" "get" "cae")
  set_tests_properties([=[get]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/src/content-assimilation-engine/omni/CMakeLists.txt;99;add_test;C:/src/content-assimilation-engine/omni/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[get]=] "C:/src/content-assimilation-engine/omni/aws/MinSizeRel/wrp.exe" "get" "cae")
  set_tests_properties([=[get]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/src/content-assimilation-engine/omni/CMakeLists.txt;99;add_test;C:/src/content-assimilation-engine/omni/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[get]=] "C:/src/content-assimilation-engine/omni/aws/RelWithDebInfo/wrp.exe" "get" "cae")
  set_tests_properties([=[get]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/src/content-assimilation-engine/omni/CMakeLists.txt;99;add_test;C:/src/content-assimilation-engine/omni/CMakeLists.txt;0;")
else()
  add_test([=[get]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[ls]=] "C:/src/content-assimilation-engine/omni/aws/Debug/wrp.exe" "ls")
  set_tests_properties([=[ls]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/src/content-assimilation-engine/omni/CMakeLists.txt;101;add_test;C:/src/content-assimilation-engine/omni/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[ls]=] "C:/src/content-assimilation-engine/omni/aws/Release/wrp.exe" "ls")
  set_tests_properties([=[ls]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/src/content-assimilation-engine/omni/CMakeLists.txt;101;add_test;C:/src/content-assimilation-engine/omni/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[ls]=] "C:/src/content-assimilation-engine/omni/aws/MinSizeRel/wrp.exe" "ls")
  set_tests_properties([=[ls]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/src/content-assimilation-engine/omni/CMakeLists.txt;101;add_test;C:/src/content-assimilation-engine/omni/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[ls]=] "C:/src/content-assimilation-engine/omni/aws/RelWithDebInfo/wrp.exe" "ls")
  set_tests_properties([=[ls]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/src/content-assimilation-engine/omni/CMakeLists.txt;101;add_test;C:/src/content-assimilation-engine/omni/CMakeLists.txt;0;")
else()
  add_test([=[ls]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[invalid]=] "C:/src/content-assimilation-engine/omni/aws/Debug/wrp.exe" "invalid")
  set_tests_properties([=[invalid]=] PROPERTIES  RETURN_VALUE "1" WILL_FAIL "TRUE" _BACKTRACE_TRIPLES "C:/src/content-assimilation-engine/omni/CMakeLists.txt;103;add_test;C:/src/content-assimilation-engine/omni/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[invalid]=] "C:/src/content-assimilation-engine/omni/aws/Release/wrp.exe" "invalid")
  set_tests_properties([=[invalid]=] PROPERTIES  RETURN_VALUE "1" WILL_FAIL "TRUE" _BACKTRACE_TRIPLES "C:/src/content-assimilation-engine/omni/CMakeLists.txt;103;add_test;C:/src/content-assimilation-engine/omni/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[invalid]=] "C:/src/content-assimilation-engine/omni/aws/MinSizeRel/wrp.exe" "invalid")
  set_tests_properties([=[invalid]=] PROPERTIES  RETURN_VALUE "1" WILL_FAIL "TRUE" _BACKTRACE_TRIPLES "C:/src/content-assimilation-engine/omni/CMakeLists.txt;103;add_test;C:/src/content-assimilation-engine/omni/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[invalid]=] "C:/src/content-assimilation-engine/omni/aws/RelWithDebInfo/wrp.exe" "invalid")
  set_tests_properties([=[invalid]=] PROPERTIES  RETURN_VALUE "1" WILL_FAIL "TRUE" _BACKTRACE_TRIPLES "C:/src/content-assimilation-engine/omni/CMakeLists.txt;103;add_test;C:/src/content-assimilation-engine/omni/CMakeLists.txt;0;")
else()
  add_test([=[invalid]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[no_cmd]=] "C:/src/content-assimilation-engine/omni/aws/Debug/wrp.exe")
  set_tests_properties([=[no_cmd]=] PROPERTIES  RETURN_VALUE "1" WILL_FAIL "TRUE" _BACKTRACE_TRIPLES "C:/src/content-assimilation-engine/omni/CMakeLists.txt;110;add_test;C:/src/content-assimilation-engine/omni/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[no_cmd]=] "C:/src/content-assimilation-engine/omni/aws/Release/wrp.exe")
  set_tests_properties([=[no_cmd]=] PROPERTIES  RETURN_VALUE "1" WILL_FAIL "TRUE" _BACKTRACE_TRIPLES "C:/src/content-assimilation-engine/omni/CMakeLists.txt;110;add_test;C:/src/content-assimilation-engine/omni/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[no_cmd]=] "C:/src/content-assimilation-engine/omni/aws/MinSizeRel/wrp.exe")
  set_tests_properties([=[no_cmd]=] PROPERTIES  RETURN_VALUE "1" WILL_FAIL "TRUE" _BACKTRACE_TRIPLES "C:/src/content-assimilation-engine/omni/CMakeLists.txt;110;add_test;C:/src/content-assimilation-engine/omni/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[no_cmd]=] "C:/src/content-assimilation-engine/omni/aws/RelWithDebInfo/wrp.exe")
  set_tests_properties([=[no_cmd]=] PROPERTIES  RETURN_VALUE "1" WILL_FAIL "TRUE" _BACKTRACE_TRIPLES "C:/src/content-assimilation-engine/omni/CMakeLists.txt;110;add_test;C:/src/content-assimilation-engine/omni/CMakeLists.txt;0;")
else()
  add_test([=[no_cmd]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[put_only]=] "C:/src/content-assimilation-engine/omni/aws/Debug/wrp.exe" "put")
  set_tests_properties([=[put_only]=] PROPERTIES  RETURN_VALUE "1" WILL_FAIL "TRUE" _BACKTRACE_TRIPLES "C:/src/content-assimilation-engine/omni/CMakeLists.txt;117;add_test;C:/src/content-assimilation-engine/omni/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[put_only]=] "C:/src/content-assimilation-engine/omni/aws/Release/wrp.exe" "put")
  set_tests_properties([=[put_only]=] PROPERTIES  RETURN_VALUE "1" WILL_FAIL "TRUE" _BACKTRACE_TRIPLES "C:/src/content-assimilation-engine/omni/CMakeLists.txt;117;add_test;C:/src/content-assimilation-engine/omni/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[put_only]=] "C:/src/content-assimilation-engine/omni/aws/MinSizeRel/wrp.exe" "put")
  set_tests_properties([=[put_only]=] PROPERTIES  RETURN_VALUE "1" WILL_FAIL "TRUE" _BACKTRACE_TRIPLES "C:/src/content-assimilation-engine/omni/CMakeLists.txt;117;add_test;C:/src/content-assimilation-engine/omni/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[put_only]=] "C:/src/content-assimilation-engine/omni/aws/RelWithDebInfo/wrp.exe" "put")
  set_tests_properties([=[put_only]=] PROPERTIES  RETURN_VALUE "1" WILL_FAIL "TRUE" _BACKTRACE_TRIPLES "C:/src/content-assimilation-engine/omni/CMakeLists.txt;117;add_test;C:/src/content-assimilation-engine/omni/CMakeLists.txt;0;")
else()
  add_test([=[put_only]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[get_only]=] "C:/src/content-assimilation-engine/omni/aws/Debug/wrp.exe" "get")
  set_tests_properties([=[get_only]=] PROPERTIES  RETURN_VALUE "1" WILL_FAIL "TRUE" _BACKTRACE_TRIPLES "C:/src/content-assimilation-engine/omni/CMakeLists.txt;124;add_test;C:/src/content-assimilation-engine/omni/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[get_only]=] "C:/src/content-assimilation-engine/omni/aws/Release/wrp.exe" "get")
  set_tests_properties([=[get_only]=] PROPERTIES  RETURN_VALUE "1" WILL_FAIL "TRUE" _BACKTRACE_TRIPLES "C:/src/content-assimilation-engine/omni/CMakeLists.txt;124;add_test;C:/src/content-assimilation-engine/omni/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[get_only]=] "C:/src/content-assimilation-engine/omni/aws/MinSizeRel/wrp.exe" "get")
  set_tests_properties([=[get_only]=] PROPERTIES  RETURN_VALUE "1" WILL_FAIL "TRUE" _BACKTRACE_TRIPLES "C:/src/content-assimilation-engine/omni/CMakeLists.txt;124;add_test;C:/src/content-assimilation-engine/omni/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[get_only]=] "C:/src/content-assimilation-engine/omni/aws/RelWithDebInfo/wrp.exe" "get")
  set_tests_properties([=[get_only]=] PROPERTIES  RETURN_VALUE "1" WILL_FAIL "TRUE" _BACKTRACE_TRIPLES "C:/src/content-assimilation-engine/omni/CMakeLists.txt;124;add_test;C:/src/content-assimilation-engine/omni/CMakeLists.txt;0;")
else()
  add_test([=[get_only]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[not_found]=] "C:/src/content-assimilation-engine/omni/aws/Debug/wrp.exe" "put" "not_found")
  set_tests_properties([=[not_found]=] PROPERTIES  RETURN_VALUE "1" WILL_FAIL "TRUE" _BACKTRACE_TRIPLES "C:/src/content-assimilation-engine/omni/CMakeLists.txt;131;add_test;C:/src/content-assimilation-engine/omni/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[not_found]=] "C:/src/content-assimilation-engine/omni/aws/Release/wrp.exe" "put" "not_found")
  set_tests_properties([=[not_found]=] PROPERTIES  RETURN_VALUE "1" WILL_FAIL "TRUE" _BACKTRACE_TRIPLES "C:/src/content-assimilation-engine/omni/CMakeLists.txt;131;add_test;C:/src/content-assimilation-engine/omni/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[not_found]=] "C:/src/content-assimilation-engine/omni/aws/MinSizeRel/wrp.exe" "put" "not_found")
  set_tests_properties([=[not_found]=] PROPERTIES  RETURN_VALUE "1" WILL_FAIL "TRUE" _BACKTRACE_TRIPLES "C:/src/content-assimilation-engine/omni/CMakeLists.txt;131;add_test;C:/src/content-assimilation-engine/omni/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[not_found]=] "C:/src/content-assimilation-engine/omni/aws/RelWithDebInfo/wrp.exe" "put" "not_found")
  set_tests_properties([=[not_found]=] PROPERTIES  RETURN_VALUE "1" WILL_FAIL "TRUE" _BACKTRACE_TRIPLES "C:/src/content-assimilation-engine/omni/CMakeLists.txt;131;add_test;C:/src/content-assimilation-engine/omni/CMakeLists.txt;0;")
else()
  add_test([=[not_found]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[nested]=] "C:/src/content-assimilation-engine/omni/aws/Debug/wrp.exe" "put" "../test/nested.yml")
  set_tests_properties([=[nested]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/src/content-assimilation-engine/omni/CMakeLists.txt;138;add_test;C:/src/content-assimilation-engine/omni/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[nested]=] "C:/src/content-assimilation-engine/omni/aws/Release/wrp.exe" "put" "../test/nested.yml")
  set_tests_properties([=[nested]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/src/content-assimilation-engine/omni/CMakeLists.txt;138;add_test;C:/src/content-assimilation-engine/omni/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[nested]=] "C:/src/content-assimilation-engine/omni/aws/MinSizeRel/wrp.exe" "put" "../test/nested.yml")
  set_tests_properties([=[nested]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/src/content-assimilation-engine/omni/CMakeLists.txt;138;add_test;C:/src/content-assimilation-engine/omni/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[nested]=] "C:/src/content-assimilation-engine/omni/aws/RelWithDebInfo/wrp.exe" "put" "../test/nested.yml")
  set_tests_properties([=[nested]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/src/content-assimilation-engine/omni/CMakeLists.txt;138;add_test;C:/src/content-assimilation-engine/omni/CMakeLists.txt;0;")
else()
  add_test([=[nested]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[empty]=] "C:/src/content-assimilation-engine/omni/aws/Debug/wrp.exe" "put" "../test/empty.yml")
  set_tests_properties([=[empty]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/src/content-assimilation-engine/omni/CMakeLists.txt;140;add_test;C:/src/content-assimilation-engine/omni/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[empty]=] "C:/src/content-assimilation-engine/omni/aws/Release/wrp.exe" "put" "../test/empty.yml")
  set_tests_properties([=[empty]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/src/content-assimilation-engine/omni/CMakeLists.txt;140;add_test;C:/src/content-assimilation-engine/omni/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[empty]=] "C:/src/content-assimilation-engine/omni/aws/MinSizeRel/wrp.exe" "put" "../test/empty.yml")
  set_tests_properties([=[empty]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/src/content-assimilation-engine/omni/CMakeLists.txt;140;add_test;C:/src/content-assimilation-engine/omni/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[empty]=] "C:/src/content-assimilation-engine/omni/aws/RelWithDebInfo/wrp.exe" "put" "../test/empty.yml")
  set_tests_properties([=[empty]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/src/content-assimilation-engine/omni/CMakeLists.txt;140;add_test;C:/src/content-assimilation-engine/omni/CMakeLists.txt;0;")
else()
  add_test([=[empty]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[root]=] "C:/src/content-assimilation-engine/omni/aws/Debug/wrp.exe" "put" "../test/root.yml")
  set_tests_properties([=[root]=] PROPERTIES  RETURN_VALUE "1" WILL_FAIL "TRUE" _BACKTRACE_TRIPLES "C:/src/content-assimilation-engine/omni/CMakeLists.txt;142;add_test;C:/src/content-assimilation-engine/omni/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[root]=] "C:/src/content-assimilation-engine/omni/aws/Release/wrp.exe" "put" "../test/root.yml")
  set_tests_properties([=[root]=] PROPERTIES  RETURN_VALUE "1" WILL_FAIL "TRUE" _BACKTRACE_TRIPLES "C:/src/content-assimilation-engine/omni/CMakeLists.txt;142;add_test;C:/src/content-assimilation-engine/omni/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[root]=] "C:/src/content-assimilation-engine/omni/aws/MinSizeRel/wrp.exe" "put" "../test/root.yml")
  set_tests_properties([=[root]=] PROPERTIES  RETURN_VALUE "1" WILL_FAIL "TRUE" _BACKTRACE_TRIPLES "C:/src/content-assimilation-engine/omni/CMakeLists.txt;142;add_test;C:/src/content-assimilation-engine/omni/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[root]=] "C:/src/content-assimilation-engine/omni/aws/RelWithDebInfo/wrp.exe" "put" "../test/root.yml")
  set_tests_properties([=[root]=] PROPERTIES  RETURN_VALUE "1" WILL_FAIL "TRUE" _BACKTRACE_TRIPLES "C:/src/content-assimilation-engine/omni/CMakeLists.txt;142;add_test;C:/src/content-assimilation-engine/omni/CMakeLists.txt;0;")
else()
  add_test([=[root]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[scalar]=] "C:/src/content-assimilation-engine/omni/aws/Debug/wrp.exe" "put" "../test/scalar.yml")
  set_tests_properties([=[scalar]=] PROPERTIES  RETURN_VALUE "1" WILL_FAIL "TRUE" _BACKTRACE_TRIPLES "C:/src/content-assimilation-engine/omni/CMakeLists.txt;149;add_test;C:/src/content-assimilation-engine/omni/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[scalar]=] "C:/src/content-assimilation-engine/omni/aws/Release/wrp.exe" "put" "../test/scalar.yml")
  set_tests_properties([=[scalar]=] PROPERTIES  RETURN_VALUE "1" WILL_FAIL "TRUE" _BACKTRACE_TRIPLES "C:/src/content-assimilation-engine/omni/CMakeLists.txt;149;add_test;C:/src/content-assimilation-engine/omni/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[scalar]=] "C:/src/content-assimilation-engine/omni/aws/MinSizeRel/wrp.exe" "put" "../test/scalar.yml")
  set_tests_properties([=[scalar]=] PROPERTIES  RETURN_VALUE "1" WILL_FAIL "TRUE" _BACKTRACE_TRIPLES "C:/src/content-assimilation-engine/omni/CMakeLists.txt;149;add_test;C:/src/content-assimilation-engine/omni/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[scalar]=] "C:/src/content-assimilation-engine/omni/aws/RelWithDebInfo/wrp.exe" "put" "../test/scalar.yml")
  set_tests_properties([=[scalar]=] PROPERTIES  RETURN_VALUE "1" WILL_FAIL "TRUE" _BACKTRACE_TRIPLES "C:/src/content-assimilation-engine/omni/CMakeLists.txt;149;add_test;C:/src/content-assimilation-engine/omni/CMakeLists.txt;0;")
else()
  add_test([=[scalar]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[invalid_yml]=] "C:/src/content-assimilation-engine/omni/aws/Debug/wrp.exe" "put" "../test/invalid.yml")
  set_tests_properties([=[invalid_yml]=] PROPERTIES  RETURN_VALUE "1" WILL_FAIL "TRUE" _BACKTRACE_TRIPLES "C:/src/content-assimilation-engine/omni/CMakeLists.txt;156;add_test;C:/src/content-assimilation-engine/omni/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[invalid_yml]=] "C:/src/content-assimilation-engine/omni/aws/Release/wrp.exe" "put" "../test/invalid.yml")
  set_tests_properties([=[invalid_yml]=] PROPERTIES  RETURN_VALUE "1" WILL_FAIL "TRUE" _BACKTRACE_TRIPLES "C:/src/content-assimilation-engine/omni/CMakeLists.txt;156;add_test;C:/src/content-assimilation-engine/omni/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[invalid_yml]=] "C:/src/content-assimilation-engine/omni/aws/MinSizeRel/wrp.exe" "put" "../test/invalid.yml")
  set_tests_properties([=[invalid_yml]=] PROPERTIES  RETURN_VALUE "1" WILL_FAIL "TRUE" _BACKTRACE_TRIPLES "C:/src/content-assimilation-engine/omni/CMakeLists.txt;156;add_test;C:/src/content-assimilation-engine/omni/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[invalid_yml]=] "C:/src/content-assimilation-engine/omni/aws/RelWithDebInfo/wrp.exe" "put" "../test/invalid.yml")
  set_tests_properties([=[invalid_yml]=] PROPERTIES  RETURN_VALUE "1" WILL_FAIL "TRUE" _BACKTRACE_TRIPLES "C:/src/content-assimilation-engine/omni/CMakeLists.txt;156;add_test;C:/src/content-assimilation-engine/omni/CMakeLists.txt;0;")
else()
  add_test([=[invalid_yml]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[path]=] "C:/src/content-assimilation-engine/omni/aws/Debug/wrp.exe" "put" "../test/path.yml")
  set_tests_properties([=[path]=] PROPERTIES  RETURN_VALUE "1" WILL_FAIL "TRUE" _BACKTRACE_TRIPLES "C:/src/content-assimilation-engine/omni/CMakeLists.txt;163;add_test;C:/src/content-assimilation-engine/omni/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[path]=] "C:/src/content-assimilation-engine/omni/aws/Release/wrp.exe" "put" "../test/path.yml")
  set_tests_properties([=[path]=] PROPERTIES  RETURN_VALUE "1" WILL_FAIL "TRUE" _BACKTRACE_TRIPLES "C:/src/content-assimilation-engine/omni/CMakeLists.txt;163;add_test;C:/src/content-assimilation-engine/omni/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[path]=] "C:/src/content-assimilation-engine/omni/aws/MinSizeRel/wrp.exe" "put" "../test/path.yml")
  set_tests_properties([=[path]=] PROPERTIES  RETURN_VALUE "1" WILL_FAIL "TRUE" _BACKTRACE_TRIPLES "C:/src/content-assimilation-engine/omni/CMakeLists.txt;163;add_test;C:/src/content-assimilation-engine/omni/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[path]=] "C:/src/content-assimilation-engine/omni/aws/RelWithDebInfo/wrp.exe" "put" "../test/path.yml")
  set_tests_properties([=[path]=] PROPERTIES  RETURN_VALUE "1" WILL_FAIL "TRUE" _BACKTRACE_TRIPLES "C:/src/content-assimilation-engine/omni/CMakeLists.txt;163;add_test;C:/src/content-assimilation-engine/omni/CMakeLists.txt;0;")
else()
  add_test([=[path]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[root_seq]=] "C:/src/content-assimilation-engine/omni/aws/Debug/wrp.exe" "put" "../test/root_seq.yml")
  set_tests_properties([=[root_seq]=] PROPERTIES  RETURN_VALUE "1" WILL_FAIL "TRUE" _BACKTRACE_TRIPLES "C:/src/content-assimilation-engine/omni/CMakeLists.txt;170;add_test;C:/src/content-assimilation-engine/omni/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[root_seq]=] "C:/src/content-assimilation-engine/omni/aws/Release/wrp.exe" "put" "../test/root_seq.yml")
  set_tests_properties([=[root_seq]=] PROPERTIES  RETURN_VALUE "1" WILL_FAIL "TRUE" _BACKTRACE_TRIPLES "C:/src/content-assimilation-engine/omni/CMakeLists.txt;170;add_test;C:/src/content-assimilation-engine/omni/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[root_seq]=] "C:/src/content-assimilation-engine/omni/aws/MinSizeRel/wrp.exe" "put" "../test/root_seq.yml")
  set_tests_properties([=[root_seq]=] PROPERTIES  RETURN_VALUE "1" WILL_FAIL "TRUE" _BACKTRACE_TRIPLES "C:/src/content-assimilation-engine/omni/CMakeLists.txt;170;add_test;C:/src/content-assimilation-engine/omni/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[root_seq]=] "C:/src/content-assimilation-engine/omni/aws/RelWithDebInfo/wrp.exe" "put" "../test/root_seq.yml")
  set_tests_properties([=[root_seq]=] PROPERTIES  RETURN_VALUE "1" WILL_FAIL "TRUE" _BACKTRACE_TRIPLES "C:/src/content-assimilation-engine/omni/CMakeLists.txt;170;add_test;C:/src/content-assimilation-engine/omni/CMakeLists.txt;0;")
else()
  add_test([=[root_seq]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[lseek]=] "C:/src/content-assimilation-engine/omni/aws/Debug/wrp.exe" "put" "../test/lseek.yml")
  set_tests_properties([=[lseek]=] PROPERTIES  RETURN_VALUE "1" WILL_FAIL "TRUE" _BACKTRACE_TRIPLES "C:/src/content-assimilation-engine/omni/CMakeLists.txt;177;add_test;C:/src/content-assimilation-engine/omni/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[lseek]=] "C:/src/content-assimilation-engine/omni/aws/Release/wrp.exe" "put" "../test/lseek.yml")
  set_tests_properties([=[lseek]=] PROPERTIES  RETURN_VALUE "1" WILL_FAIL "TRUE" _BACKTRACE_TRIPLES "C:/src/content-assimilation-engine/omni/CMakeLists.txt;177;add_test;C:/src/content-assimilation-engine/omni/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[lseek]=] "C:/src/content-assimilation-engine/omni/aws/MinSizeRel/wrp.exe" "put" "../test/lseek.yml")
  set_tests_properties([=[lseek]=] PROPERTIES  RETURN_VALUE "1" WILL_FAIL "TRUE" _BACKTRACE_TRIPLES "C:/src/content-assimilation-engine/omni/CMakeLists.txt;177;add_test;C:/src/content-assimilation-engine/omni/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[lseek]=] "C:/src/content-assimilation-engine/omni/aws/RelWithDebInfo/wrp.exe" "put" "../test/lseek.yml")
  set_tests_properties([=[lseek]=] PROPERTIES  RETURN_VALUE "1" WILL_FAIL "TRUE" _BACKTRACE_TRIPLES "C:/src/content-assimilation-engine/omni/CMakeLists.txt;177;add_test;C:/src/content-assimilation-engine/omni/CMakeLists.txt;0;")
else()
  add_test([=[lseek]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[hash]=] "C:/src/content-assimilation-engine/omni/aws/Debug/wrp.exe" "put" "../test/hash.yml")
  set_tests_properties([=[hash]=] PROPERTIES  RETURN_VALUE "1" WILL_FAIL "TRUE" _BACKTRACE_TRIPLES "C:/src/content-assimilation-engine/omni/CMakeLists.txt;185;add_test;C:/src/content-assimilation-engine/omni/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[hash]=] "C:/src/content-assimilation-engine/omni/aws/Release/wrp.exe" "put" "../test/hash.yml")
  set_tests_properties([=[hash]=] PROPERTIES  RETURN_VALUE "1" WILL_FAIL "TRUE" _BACKTRACE_TRIPLES "C:/src/content-assimilation-engine/omni/CMakeLists.txt;185;add_test;C:/src/content-assimilation-engine/omni/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[hash]=] "C:/src/content-assimilation-engine/omni/aws/MinSizeRel/wrp.exe" "put" "../test/hash.yml")
  set_tests_properties([=[hash]=] PROPERTIES  RETURN_VALUE "1" WILL_FAIL "TRUE" _BACKTRACE_TRIPLES "C:/src/content-assimilation-engine/omni/CMakeLists.txt;185;add_test;C:/src/content-assimilation-engine/omni/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[hash]=] "C:/src/content-assimilation-engine/omni/aws/RelWithDebInfo/wrp.exe" "put" "../test/hash.yml")
  set_tests_properties([=[hash]=] PROPERTIES  RETURN_VALUE "1" WILL_FAIL "TRUE" _BACKTRACE_TRIPLES "C:/src/content-assimilation-engine/omni/CMakeLists.txt;185;add_test;C:/src/content-assimilation-engine/omni/CMakeLists.txt;0;")
else()
  add_test([=[hash]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[http]=] "C:/src/content-assimilation-engine/omni/aws/Debug/wrp.exe" "put" "../test/http.yml")
  set_tests_properties([=[http]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/src/content-assimilation-engine/omni/CMakeLists.txt;192;add_test;C:/src/content-assimilation-engine/omni/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[http]=] "C:/src/content-assimilation-engine/omni/aws/Release/wrp.exe" "put" "../test/http.yml")
  set_tests_properties([=[http]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/src/content-assimilation-engine/omni/CMakeLists.txt;192;add_test;C:/src/content-assimilation-engine/omni/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[http]=] "C:/src/content-assimilation-engine/omni/aws/MinSizeRel/wrp.exe" "put" "../test/http.yml")
  set_tests_properties([=[http]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/src/content-assimilation-engine/omni/CMakeLists.txt;192;add_test;C:/src/content-assimilation-engine/omni/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[http]=] "C:/src/content-assimilation-engine/omni/aws/RelWithDebInfo/wrp.exe" "put" "../test/http.yml")
  set_tests_properties([=[http]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/src/content-assimilation-engine/omni/CMakeLists.txt;192;add_test;C:/src/content-assimilation-engine/omni/CMakeLists.txt;0;")
else()
  add_test([=[http]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[redi]=] "C:/src/content-assimilation-engine/omni/aws/Debug/wrp.exe" "put" "../test/redi.yml")
  set_tests_properties([=[redi]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/src/content-assimilation-engine/omni/CMakeLists.txt;193;add_test;C:/src/content-assimilation-engine/omni/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[redi]=] "C:/src/content-assimilation-engine/omni/aws/Release/wrp.exe" "put" "../test/redi.yml")
  set_tests_properties([=[redi]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/src/content-assimilation-engine/omni/CMakeLists.txt;193;add_test;C:/src/content-assimilation-engine/omni/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[redi]=] "C:/src/content-assimilation-engine/omni/aws/MinSizeRel/wrp.exe" "put" "../test/redi.yml")
  set_tests_properties([=[redi]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/src/content-assimilation-engine/omni/CMakeLists.txt;193;add_test;C:/src/content-assimilation-engine/omni/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[redi]=] "C:/src/content-assimilation-engine/omni/aws/RelWithDebInfo/wrp.exe" "put" "../test/redi.yml")
  set_tests_properties([=[redi]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/src/content-assimilation-engine/omni/CMakeLists.txt;193;add_test;C:/src/content-assimilation-engine/omni/CMakeLists.txt;0;")
else()
  add_test([=[redi]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[rget]=] "C:/src/content-assimilation-engine/omni/aws/Debug/wrp.exe" "put" "../test/rget.yml")
  set_tests_properties([=[rget]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/src/content-assimilation-engine/omni/CMakeLists.txt;194;add_test;C:/src/content-assimilation-engine/omni/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[rget]=] "C:/src/content-assimilation-engine/omni/aws/Release/wrp.exe" "put" "../test/rget.yml")
  set_tests_properties([=[rget]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/src/content-assimilation-engine/omni/CMakeLists.txt;194;add_test;C:/src/content-assimilation-engine/omni/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[rget]=] "C:/src/content-assimilation-engine/omni/aws/MinSizeRel/wrp.exe" "put" "../test/rget.yml")
  set_tests_properties([=[rget]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/src/content-assimilation-engine/omni/CMakeLists.txt;194;add_test;C:/src/content-assimilation-engine/omni/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[rget]=] "C:/src/content-assimilation-engine/omni/aws/RelWithDebInfo/wrp.exe" "put" "../test/rget.yml")
  set_tests_properties([=[rget]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/src/content-assimilation-engine/omni/CMakeLists.txt;194;add_test;C:/src/content-assimilation-engine/omni/CMakeLists.txt;0;")
else()
  add_test([=[rget]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[globus]=] "C:/src/content-assimilation-engine/omni/aws/Debug/wrp.exe" "put" "../test/globus.yml")
  set_tests_properties([=[globus]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/src/content-assimilation-engine/omni/CMakeLists.txt;195;add_test;C:/src/content-assimilation-engine/omni/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[globus]=] "C:/src/content-assimilation-engine/omni/aws/Release/wrp.exe" "put" "../test/globus.yml")
  set_tests_properties([=[globus]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/src/content-assimilation-engine/omni/CMakeLists.txt;195;add_test;C:/src/content-assimilation-engine/omni/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[globus]=] "C:/src/content-assimilation-engine/omni/aws/MinSizeRel/wrp.exe" "put" "../test/globus.yml")
  set_tests_properties([=[globus]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/src/content-assimilation-engine/omni/CMakeLists.txt;195;add_test;C:/src/content-assimilation-engine/omni/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[globus]=] "C:/src/content-assimilation-engine/omni/aws/RelWithDebInfo/wrp.exe" "put" "../test/globus.yml")
  set_tests_properties([=[globus]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/src/content-assimilation-engine/omni/CMakeLists.txt;195;add_test;C:/src/content-assimilation-engine/omni/CMakeLists.txt;0;")
else()
  add_test([=[globus]=] NOT_AVAILABLE)
endif()
