name: point
tags:
  - "my first data point"
  - "my first 3D dataset"
  - "my HDF5 file"

uri: "hdf5://../data/A46_xx.h5/data/axis1"
start: [0]
count: [20]
stride: [5]

# run: h5topq.sh

# dest: s3://mybucket/point.parquet
