name: "OMNI Job with HDF5 Support"
max_scale: 100

data:
  # Regular file entry
  - path: "~/data/sample_files/*.txt"
    offset: 0
    size: 1024
    description: ["text files", "sample data"]
    hash: "abc123"

  # HDF5 URI entry
  - uri: "hdf5://../data/A46_xx.h5/data/block0_values"
    start: [0, 0]
    count: [1, 3]
    stride: [1, 1]
    description: ["HDF5 dataset", "2D data"]
    run: "h5topq.sh"
    dest: "s3://mybucket/point.parquet"

  # Another HDF5 entry
  - uri: "hdf5://../data/simulation.h5/results/temperature"
    start: [0, 0, 0]
    count: [100, 100, 50]
    stride: [1, 1, 1]
    description: ["temperature data", "3D simulation results"]
    dest: "s3://mybucket/temperature.parquet"
