# OMNI job to load entire TERRA HDF5 file
name: terra_hdf5_full_load
max_scale: 8  # Use up to 8 processes for large file processing
data:
- path: ~/Downloads/TERRA_BF_L1B_O10204_20011118010522_F000_V001.h5
  offset: 0  # Start from beginning of file
  # size omitted to read entire file
  description:
    - hdf5
    - binary
    - satellite_data
    - terra_modis
    - level1b
    - scientific_data
    - remote_sensing
    - earth_observation
  hash: terra_hdf5_full_file  # Identifier for this data load 