name: tf
tags:
  - "terra fusion"
  - "2D dataset"
  - "HDF5 file"

uri: "hdf5:///mnt/common/datasets-staging/TERRA_BF_L1B_O10204_20011118010522_F000_V001.h5/ASTER/granule_11182001013943/SWIR/Geolocation/Latitude"
start: [0, 0]
count: [1, 3]
stride: [1, 1]

# run: h5topq.sh

# dest: s3://mybucket/point.parquet
