name: "tf3d_new_format"
max_scale: 100

data:
  # HDF5 URI entry for 3D dataset
  - uri: "hdf5:///mnt/common/datasets-staging/TERRA_BF_L1B_O10204_20011118010522_F000_V001.h5/MOPITT/granule_20011118/Geolocation/Latitude"
    start: [0, 0, 0]
    count: [1, 3, 2]
    stride: [1, 1, 1]
    description: ["terra fusion", "3D dataset", "HDF5 file"]
    run: "h5topq.sh"
    dest: "s3://mybucket/point.parquet"
