package:
  name: omni
  version: 0.0.0

source:
  path: .
#  git_url: https://github.com/iowarp/content-assimilation-engine
#  git_depth: 1

requirements:
  build:
    - aws-sdk-cpp 1.11.*
    - poco    
    - pyaml    
  run:
    - aws-sdk-cpp 1.11.*
    - poco
    - pyaml


files:
  - README.md
  - ./bin/*

test:
  requires:
    - aws-sdk-cpp 1.11.*
    - poco
    - pyaml
  commands:
    - wrp

about:
  home: https://grc.iit.edu/research/projects/iowarp/
  license: BSD
  summary: IOWarp OMNI Conda Package
