all:
	gcc globus_download.c -o globus_download -I/opt/hdfeos/iowarp/include -L/opt/hdfeos/iowarp/lib -lglobus_ftp_client -lglobus_common -lglobus_gsi_cert_utils -lglobus_gsi_credential -lglobus_gsi_proxy_core -lglobus_gsi_sysconfig -lglobus_gsi_callback -lglobus_openssl -lglobus_xio -lssl -lcrypto -lpthread 
