name: point
tags:
  - "first row"
  - "2D dataset"
  - "HDF5 file from CSV"

uri: "hdf5://../data/A46_xx.h5/data/block0_values"
start: [0, 0]
count: [1, 3]
stride: [1, 1]

# run: h5topq.sh

# dest: s3://mybucket/point.parquet
