# CMake generated Testfile for 
# Source directory: /home/hyoklee/content-assimilation-engine/omni-old
# Build directory: /home/hyoklee/content-assimilation-engine/omni-old/poco
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[put]=] "/home/hyoklee/content-assimilation-engine/omni-old/poco/wrp" "put" "../test/posix.yml")
set_tests_properties([=[put]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/hyoklee/content-assimilation-engine/omni-old/CMakeLists.txt;97;add_test;/home/hyoklee/content-assimilation-engine/omni-old/CMakeLists.txt;0;")
add_test([=[get]=] "/home/hyoklee/content-assimilation-engine/omni-old/poco/wrp" "get" "cae")
set_tests_properties([=[get]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/hyoklee/content-assimilation-engine/omni-old/CMakeLists.txt;99;add_test;/home/hyoklee/content-assimilation-engine/omni-old/CMakeLists.txt;0;")
add_test([=[ls]=] "/home/hyoklee/content-assimilation-engine/omni-old/poco/wrp" "ls")
set_tests_properties([=[ls]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/hyoklee/content-assimilation-engine/omni-old/CMakeLists.txt;101;add_test;/home/hyoklee/content-assimilation-engine/omni-old/CMakeLists.txt;0;")
add_test([=[invalid]=] "/home/hyoklee/content-assimilation-engine/omni-old/poco/wrp" "invalid")
set_tests_properties([=[invalid]=] PROPERTIES  RETURN_VALUE "1" WILL_FAIL "TRUE" _BACKTRACE_TRIPLES "/home/hyoklee/content-assimilation-engine/omni-old/CMakeLists.txt;103;add_test;/home/hyoklee/content-assimilation-engine/omni-old/CMakeLists.txt;0;")
add_test([=[no_cmd]=] "/home/hyoklee/content-assimilation-engine/omni-old/poco/wrp")
set_tests_properties([=[no_cmd]=] PROPERTIES  RETURN_VALUE "1" WILL_FAIL "TRUE" _BACKTRACE_TRIPLES "/home/hyoklee/content-assimilation-engine/omni-old/CMakeLists.txt;110;add_test;/home/hyoklee/content-assimilation-engine/omni-old/CMakeLists.txt;0;")
add_test([=[put_only]=] "/home/hyoklee/content-assimilation-engine/omni-old/poco/wrp" "put")
set_tests_properties([=[put_only]=] PROPERTIES  RETURN_VALUE "1" WILL_FAIL "TRUE" _BACKTRACE_TRIPLES "/home/hyoklee/content-assimilation-engine/omni-old/CMakeLists.txt;117;add_test;/home/hyoklee/content-assimilation-engine/omni-old/CMakeLists.txt;0;")
add_test([=[get_only]=] "/home/hyoklee/content-assimilation-engine/omni-old/poco/wrp" "get")
set_tests_properties([=[get_only]=] PROPERTIES  RETURN_VALUE "1" WILL_FAIL "TRUE" _BACKTRACE_TRIPLES "/home/hyoklee/content-assimilation-engine/omni-old/CMakeLists.txt;124;add_test;/home/hyoklee/content-assimilation-engine/omni-old/CMakeLists.txt;0;")
add_test([=[not_found]=] "/home/hyoklee/content-assimilation-engine/omni-old/poco/wrp" "put" "not_found")
set_tests_properties([=[not_found]=] PROPERTIES  RETURN_VALUE "1" WILL_FAIL "TRUE" _BACKTRACE_TRIPLES "/home/hyoklee/content-assimilation-engine/omni-old/CMakeLists.txt;131;add_test;/home/hyoklee/content-assimilation-engine/omni-old/CMakeLists.txt;0;")
add_test([=[nested]=] "/home/hyoklee/content-assimilation-engine/omni-old/poco/wrp" "put" "../test/nested.yml")
set_tests_properties([=[nested]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/hyoklee/content-assimilation-engine/omni-old/CMakeLists.txt;138;add_test;/home/hyoklee/content-assimilation-engine/omni-old/CMakeLists.txt;0;")
add_test([=[empty]=] "/home/hyoklee/content-assimilation-engine/omni-old/poco/wrp" "put" "../test/empty.yml")
set_tests_properties([=[empty]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/hyoklee/content-assimilation-engine/omni-old/CMakeLists.txt;140;add_test;/home/hyoklee/content-assimilation-engine/omni-old/CMakeLists.txt;0;")
add_test([=[root]=] "/home/hyoklee/content-assimilation-engine/omni-old/poco/wrp" "put" "../test/root.yml")
set_tests_properties([=[root]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/hyoklee/content-assimilation-engine/omni-old/CMakeLists.txt;142;add_test;/home/hyoklee/content-assimilation-engine/omni-old/CMakeLists.txt;0;")
add_test([=[scalar]=] "/home/hyoklee/content-assimilation-engine/omni-old/poco/wrp" "put" "../test/scalar.yml")
set_tests_properties([=[scalar]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/hyoklee/content-assimilation-engine/omni-old/CMakeLists.txt;144;add_test;/home/hyoklee/content-assimilation-engine/omni-old/CMakeLists.txt;0;")
add_test([=[invalid_yml]=] "/home/hyoklee/content-assimilation-engine/omni-old/poco/wrp" "put" "../test/invalid.yml")
set_tests_properties([=[invalid_yml]=] PROPERTIES  RETURN_VALUE "1" WILL_FAIL "TRUE" _BACKTRACE_TRIPLES "/home/hyoklee/content-assimilation-engine/omni-old/CMakeLists.txt;146;add_test;/home/hyoklee/content-assimilation-engine/omni-old/CMakeLists.txt;0;")
add_test([=[path]=] "/home/hyoklee/content-assimilation-engine/omni-old/poco/wrp" "put" "../test/path.yml")
set_tests_properties([=[path]=] PROPERTIES  RETURN_VALUE "1" WILL_FAIL "TRUE" _BACKTRACE_TRIPLES "/home/hyoklee/content-assimilation-engine/omni-old/CMakeLists.txt;153;add_test;/home/hyoklee/content-assimilation-engine/omni-old/CMakeLists.txt;0;")
add_test([=[root_seq]=] "/home/hyoklee/content-assimilation-engine/omni-old/poco/wrp" "put" "../test/root_seq.yml")
set_tests_properties([=[root_seq]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/hyoklee/content-assimilation-engine/omni-old/CMakeLists.txt;159;add_test;/home/hyoklee/content-assimilation-engine/omni-old/CMakeLists.txt;0;")
add_test([=[lseek]=] "/home/hyoklee/content-assimilation-engine/omni-old/poco/wrp" "put" "../test/lseek.yml")
set_tests_properties([=[lseek]=] PROPERTIES  RETURN_VALUE "1" WILL_FAIL "TRUE" _BACKTRACE_TRIPLES "/home/hyoklee/content-assimilation-engine/omni-old/CMakeLists.txt;161;add_test;/home/hyoklee/content-assimilation-engine/omni-old/CMakeLists.txt;0;")
add_test([=[hash]=] "/home/hyoklee/content-assimilation-engine/omni-old/poco/wrp" "put" "../test/hash.yml")
set_tests_properties([=[hash]=] PROPERTIES  RETURN_VALUE "1" WILL_FAIL "TRUE" _BACKTRACE_TRIPLES "/home/hyoklee/content-assimilation-engine/omni-old/CMakeLists.txt;169;add_test;/home/hyoklee/content-assimilation-engine/omni-old/CMakeLists.txt;0;")
add_test([=[http]=] "/home/hyoklee/content-assimilation-engine/omni-old/poco/wrp" "put" "../test/http.yml")
set_tests_properties([=[http]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/hyoklee/content-assimilation-engine/omni-old/CMakeLists.txt;176;add_test;/home/hyoklee/content-assimilation-engine/omni-old/CMakeLists.txt;0;")
add_test([=[redi]=] "/home/hyoklee/content-assimilation-engine/omni-old/poco/wrp" "put" "../test/redi.yml")
set_tests_properties([=[redi]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/hyoklee/content-assimilation-engine/omni-old/CMakeLists.txt;177;add_test;/home/hyoklee/content-assimilation-engine/omni-old/CMakeLists.txt;0;")
add_test([=[rget]=] "/home/hyoklee/content-assimilation-engine/omni-old/poco/wrp" "put" "../test/rget.yml")
set_tests_properties([=[rget]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/hyoklee/content-assimilation-engine/omni-old/CMakeLists.txt;178;add_test;/home/hyoklee/content-assimilation-engine/omni-old/CMakeLists.txt;0;")
