name: IOWarp Install and Build

on:
  workflow_dispatch:
  push:
    branches: [main-]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  iowarp-setup:
    runs-on: ubuntu-latest
    env:
      IOWARP: ${{ github.workspace }}/iowarp
      GITHUB_USERNAME: hyoklee
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: apt
        run: |
          sudo apt-get update
          sudo apt-get install -y libyaml-cpp-dev \
          libopenmpi-dev openmpi-bin libhdf5-dev

      - name: clone
        run: |
          mkdir -p "${IOWARP}"
          git clone https://github.com/iowarp/iowarp-install.git "${IOWARP}/iowarp-install"

      - name: configure-git-lfs
        run: |
          git config --global credential.helper store
          echo "https://${GITHUB_USERNAME}:${GITHUB_TOKEN}@github.com" > ~/.git-credentials
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: spack
        run: |
          cd "${IOWARP}/iowarp-install"
          pip3 install -r requirements.txt
          chmod +x wrpgit
          ./wrpgit init
          yq eval '
            .username = strenv(GITHUB_USERNAME) |
            .protocol = "https" |
            .token = strenv(GITHUB_TOKEN) |
            .modules[].fork = false
          ' -i wrpgit.yaml
          ./wrpgit clone
          git clone https://github.com/spack/spack.git  -b v0.23.0 "${HOME}/spack"
          source "${HOME}/spack/share/spack/setup-env.sh"
          spack repo add "${IOWARP}/iowarp-install/iowarp-spack"
          spack external find
          spack config add "modules:default:enable:[lmod]"
          spack install lmod
          source $(spack location -i lmod)/lmod/lmod/init/bash
          export MODULEPATH=$SPACK_ROOT/share/spack/lmod/linux-ubuntu24.04-x86_64/Core
          spack install mpi
          spack load mpi
          spack install hdf5
          spack load hdf5
          spack install iowarp
          spack load iowarp
          module use $MODULEPATH
          module spider
          module avail
          module list
          cd "${IOWARP}/iowarp-install"
          pip install -r requirements.txt
          ./wrpgit setup
          ./wrpgit build
          which scspkg
          SCSPKG_MODULE_DIR=$(scspkg module dir)
          which jarvis
          module use ${SCSPKG_MODULE_DIR}
          module spider
          module avail
          module load content-transfer-engine
          module load content-assimilation-engine
          module load ppi-chi-nettest
          module load ppi-jarvis-util
          module load ppi-jarvis-cd
          module load iowarp-runtime-util
          module list
          jarvis bootstrap from local
          sleep 5
          jarvis rg build
          sleep 5
          jarvis repo list
          jarvis env build jarvis_wrp_cae
          jarvis env build hermes
          find ${IOWARP} -name '*.yaml'
          find ${HOME}/.jarvis
          find ${HOME}/.scspkg
          pwd
          jarvis ppl create test_omni
