name: IOWarp Install and Build

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  iowarp-setup:
    runs-on: ubuntu-latest
    env:
      IOWARP: ${{ github.workspace }}/iowarp
      GITHUB_USERNAME: hyoklee
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: apt
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip git libyaml-cpp-dev \
          libopenmpi-dev openmpi-bin

      - name: spack
        run: |
          git clone https://github.com/spack/spack.git  -b v0.23.0 "${HOME}/spack"
          source "${HOME}/spack/share/spack/setup-env.sh"
          spack repo add "${IOWARP}/iowarp-install/iowarp-spack"
          spack external find
          spack install hdf5
          spack load hdf5
          spack install iowarp
          spack load iowarp

      - name: yq
        run: |
          sudo wget -O /usr/bin/yq "https://github.com/mikefarah/yq/releases/download/v4.43.1/yq_linux_amd64"
          sudo chmod +x /usr/bin/yq

      - name: clone
        run: |
          mkdir -p "${IOWARP}"
          git clone https://github.com/iowarp/iowarp-install.git "${IOWARP}/iowarp-install"

      - name: pip3
        run: |
          cd "${IOWARP}/iowarp-install"
          pip3 install -r requirements.txt
          chmod +x wrpgit

      - name: init
        run: |
          cd "${IOWARP}/iowarp-install"
          ./wrpgit init

      # - name: Patch wrpgit.yaml for forking
      #   run: |
      #     cd "${IOWARP}/iowarp-install"
      #     yq eval '
      #       .username = strenv(GITHUB_USERNAME) |
      #       .protocol = "https" |
      #       .token = strenv(GITHUB_TOKEN) |
      #       .modules[].fork = true
      #     ' -i wrpgit.yaml

      - name: patch
        run: |
          cd "${IOWARP}/iowarp-install"
          yq eval '
            .username = strenv(GITHUB_USERNAME) |
            .protocol = "https" |
            .token = strenv(GITHUB_TOKEN) |
            .modules[].fork = false
          ' -i wrpgit.yaml

#      - name: Fork IOWarp repos
#        run: |
#          cd "${IOWARP}/iowarp-install"
#          ./wrpgit fork

      - name: clone
        run: |
          cd "${IOWARP}/iowarp-install"
          ./wrpgit clone


      - name: setup
        run: |
          source "${HOME}/spack/share/spack/setup-env.sh"
          cd "${IOWARP}/iowarp-install"
          spack load iowarp
          pip3 install -r requirements.txt
          ./wrpgit setup

      - name: build
        run: |
          cd "${IOWARP}/iowarp-install"
          source "${HOME}/spack/share/spack/setup-env.sh"
          spack load iowarp
          spack load hdf5
          pip3 install -r requirements.txt
          ./wrpgit build
          ls $HOME/.scspkg/modulefiles

      - name: clean
        run: |
          cd "${IOWARP}/iowarp-install"
          ./wrpgit clean

      - name: recreate
        run: |
          cd "${IOWARP}/iowarp-install"
          ./wrpgit recreate
