name: mac omni r

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-13, macos-14, macos-15, macos-26]
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: install
        run: |
          brew install poco yaml-cpp nlohmann-json
      - name: test
        run: |
          cd omni
          mkdir build
          cd build
          cmake -DSITE:STRING="${{ matrix.os }}" -DBUILDNAME="omni/r" ..
          ctest -C Release -D Experimental
          cd ../..
      - name: poco
        run: |
          cd omni
          mkdir poco
          cd poco
          cmake -DUSE_POCO=ON -DSITE:STRING="${{ matrix.os }}" -DBUILDNAME="omni/r/poco" ..
          ctest -C Release -D Experimental

