name: ubu omni r

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-22.04]    
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: install
      run: |
        sudo apt-get install -y libpoco-dev libyaml-cpp-dev nlohmann-json3-dev
        sudo apt-get install -y python3-pip python3-venv
    - name: test
      run: |
          cd omni-old
          mkdir build
          cd build
          cmake  -DSITE:STRING="${{ matrix.os }}" -DBUILDNAME="omni/r" ..
          ctest -C Release -D Experimental
          cd ../..
    - name: poco
      run: |
          cd omni-old
          mkdir poco
          cd poco
          cmake -DUSE_POCO=ON  -DSITE:STRING="${{ matrix.os }}" -DBUILDNAME="omni/r/poco" ..
          ctest -C Release -D Experimental
