name: ubuntu-24.04 spack-0.23.0

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: checkout spack
      uses: actions/checkout@v4
      with:
        repository: spack/spack
        ref: v0.23.0
        path: ./spack
    - name: checkout iowarp-install
      uses: actions/checkout@v4
      with:
        repository: iowarp/iowarp-install
        path: ./iowarp-install
    - name: cmake
      uses: lukka/get-cmake@latest
      with:
        cmakeVersion: 3.31.5
        ninjaVersion: 1.12.1
    - name: module load
      run: |
        sudo apt install -y lmod
        ls /etc/profile.d/
        source /etc/profile.d/lmod.sh
        module avail
        module list
    - name: spack
      run: |
        . ./spack/share/spack/setup-env.sh
        spack external find
        cd ./iowarp-install/
        spack repo add iowarp-spack
        spack install iowarp@main +vfd +mpiio +compress +encrypt ^cmake@3.31.5
    - name: test module
      run: |
        . ./spack/share/spack/setup-env.sh
        spack load iowarp
        chi_make_repo ~/my_mod_repo example
        chi_make_mod ~/my_mod_repo/compressor
        scspkg create compressor
        chi_refresh_repo ~/my_mod_repo
        cd ~/my_mod_repo
        mkdir build
        cd build
        cmake ..  -DCMAKE_INSTALL_PREFIX=$(scspkg pkg root example)
        make -j
    - name: test jarvis
      env:
        FI_PROVIDER: "sockets"
        HG_LOG_LEVEL: "debug"
      run: |
        pwd
        . ./spack/share/spack/setup-env.sh
        spack load iowarp
        jarvis bootstrap from local
        jarvis rg build
        mkdir -p ~/my_mod_repo/jarvis_example/jarvis_example
        mkdir -p ~/my_mod_repo/jarvis_example/pipelines
        jarvis repo add ~/my_mod_repo/jarvis_example
        jarvis repo create compressor app
        tree ~/my_mod_repo/
    - name: test cae
      run: |
        . ./spack/share/spack/setup-env.sh
        spack load iowarp
        spack load hdf5
        cmake -DCMAKE_INSTALL_PREFIX=$(scspkg pkg root example) --preset debug
        cd build
        ninja
        ninja install
    - name: load chmaera_run
      run: |
        source /etc/profile.d/lmod.sh
        module avail
        module list
        . ./spack/share/spack/setup-env.sh
        spack load iowarp
        module avail
        module list
        module load chimaera_run
        module avail
        module list
    - name: jarvis hermes
      run: |
        . ./spack/share/spack/setup-env.sh
        spack load iowarp
        module load chimaera_run
        jarvis env build hermes
        jarvis ppl index load jarvis_hermes.hermes.test_hermes
    - name: test pkg
      run: |
        . ./spack/share/spack/setup-env.sh
        spack load iowarp
        jarvis pkg conf chimaera_run data_shm=500m rdata_shm=500m task_shm=500m qdepth=50 worker_cpus=[0,1,1]
        jarvis ppl print
        cat $(jarvis path +shared)/chimaera_run/hostfile
        cat $(jarvis path +shared)/chimaera_run/chimaera_server.yaml
        ctest -VV
