name: ubuntu-24.04 spack-0.23.0

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: checkout spack
      uses: actions/checkout@v4
      with:
        repository: spack/spack
        ref: v0.23.0
        path: ./spack
    - name: checkout iowarp-install
      uses: actions/checkout@v4
      with:
        repository: iowarp/iowarp-install
        path: ./iowarp-install
    - name: cmake
      uses: lukka/get-cmake@latest
      with:
        cmakeVersion: 3.31.5
    - name: install iowarp
      run: |
        sudo apt install -y ninja-build
        . ./spack/share/spack/setup-env.sh
        spack external find
        cd ./iowarp-install/
        spack repo add iowarp-spack
        spack install iowarp+posix ^cmake@3.31.5
    - name: test module
      run: |
        . ./spack/share/spack/setup-env.sh
        spack load iowarp+posix
        chi_make_repo ~/my_mod_repo example
        chi_make_mod ~/my_mod_repo/compressor
        chi_refresh_repo ~/my_mod_repo
        cd ~/my_mod_repo
        mkdir build
        cd build
        cmake ..
        make -j
    - name: test jarvis
      run: |
        pwd
        . ./spack/share/spack/setup-env.sh
        spack load iowarp+posix
        jarvis bootstrap from local
        jarvis rg build
    - name: test cae
      run: |
        . ./spack/share/spack/setup-env.sh
        spack load iowarp+posix
        mkdir build
        cd build
        cmake ..
        make
    - name: test engine
      run: |
        pwd
        . ./spack/share/spack/setup-env.sh
        spack load iowarp+posix
        cd engine
        mkdir build
        cd build
        cmake ..
        make
