name: win omni r

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: install
        run: |
          vcpkg install poco[crypto,netssl] yaml-cpp
          vcpkg integrate install
      - name: test
        run: |
          cd omni
          mkdir build
          cd build
          cmake -DCMAKE_TOOLCHAIN_FILE="C:/vcpkg/scripts/buildsystems/vcpkg.cmake" -DSITE:STRING="win" -DBUILDNAME="omni/r" ..
          ctest -C Release -D Experimental
          cd ../..
        shell: cmd
      - name: poco
        run: |
          cd omni
          mkdir poco
          cd poco
          cmake -DPOCO=ON -DCMAKE_TOOLCHAIN_FILE="C:/vcpkg/scripts/buildsystems/vcpkg.cmake" -DSITE:STRING="win" -DBUILDNAME="omni/r/poco" ..
          ctest -C Release -D Experimental
        shell: cmd
