name: win omni r

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2022, windows-2025]        
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: install
        run: |
          vcpkg install poco[crypto,netssl] yaml-cpp nlohmann-json
          vcpkg integrate install
      - name: test
        run: |
          cd omni-old
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE="C:/vcpkg/scripts/buildsystems/vcpkg.cmake" -DSITE:STRING="${{ matrix.os }}" -DBUILDNAME="omni/r" ..
          ctest -C Release -D Experimental
          cd ../..
        shell: cmd
      - name: poco
        run: |
          cd omni-old
          mkdir poco
          cd poco
          cmake -DUSE_POCO=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE="C:/vcpkg/scripts/buildsystems/vcpkg.cmake" -DSITE:STRING="${{ matrix.os }}" -DBUILDNAME="omni/r/poco" ..
          ctest -C Release -D Experimental
        shell: cmd
